// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aejuqvqbcxqsxnlomkwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlanVxdnFiY3hxc3hubG9ta3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MDczNzYsImV4cCI6MjA1NDQ4MzM3Nn0.bZCgZVIqQsp8uPNsMj2FtHIEwZj3PHtTRytvYtAmm4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);